version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: koel_nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker-compose/nginx/koel.castorsoft.com.br.conf.template:/etc/nginx/templates/koel.castorsoft.com.br.conf.template
      - ./:/var/www/app/
      - ./.docker-compose/certs/castorsoft.com.br.key:/etc/nginx/ssl/castorsoft.com.br.key
      - ./.docker-compose/certs/castorsoft.com.br.crt:/etc/nginx/ssl/castorsoft.com.br.crt
    environment:
      - NGINX_HOST=${SERVER_NAME}
    networks:
      network:
  app:
    build:
      context: .
    image: koel-app
    container_name: koel_app
    restart: always
    tty: true
    working_dir: /var/www/app/
    volumes:
      - ./:/var/www/app/
      - ./.docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      network:

  db:
    image: postgres:16-alpine
    container_name: koel_db
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      network:
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge