version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: koel_nginx
    restart: always
    tty: true
    ports:
      - "84:80"
      - "444:443"
    volumes:
      - ./.docker-compose/nginx/koel.castorsoft.com.br.conf.template:/etc/nginx/templates/koel.castorsoft.com.br.conf.template
      - ./:/var/www/app/
      - ./certs/privkey1.pem:/etc/nginx/ssl/castorsoft.com.br.privkey.pem
      - ./certs/fullchain1.pem:/etc/nginx/ssl/castorsoft.com.br.fullchain.pem
    environment:
      - NGINX_HOST=${APP_URL}
    networks:
      network:
  app:
    build:
      context: .
    image: koel-app
    container_name: koel_app
    restart: always
    tty: true
    working_dir: /var/www/app/
    volumes:
      - ./:/var/www/app/
      - ./.docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      network:

  db:
    image: mysql:alpine
    container_name: koel_db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      network:
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge